name: oil-anomaly-project
channels:
  - defaults
dependencies:
  - python=3.11.14
  - pip
  - pip:
    - numpy==2.3.4
    - pandas==2.3.3
    - scipy==1.16.3
    - scikit-learn==1.7.2
    - tensorflow==2.20.0
    - keras==3.12.0
    - tensorboard==2.20.0
    - matplotlib==3.10.7
    - seaborn==0.13.2
    - jupyterlab==4.4.10
    - ipykernel==7.1.0
    - h5py==3.15.1  
    - pyarrow==21.0.0
